services:
  backend:
    build:
      context: .
      dockerfile: Courses/Dockerfile
    ports:
      - 8080:8080
    environment:
      ConnectionStrings__AppDbContext: "Host=pg; Password=postgres; Username=postgres; Database=courses_prod"
      ASPNETCORE_ENVIRONMENT: Production

  web:
    build:
      context: .
      dockerfile: CoursesWeb/Dockerfile
    ports:
      - 3000:3000
    environment:
      BACKEND_URL: "backend:8080"

  pg:
    image: postgres:18

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: { }
